server:
  port: 8888
spring:
  thymeleaf:
    # 关闭缓存
    cache: false
  profiles:
    active: dev
  # swagger配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.73:3306/seckill?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: mizhuo123
    hikari:
      # 连接池名称
      pool-name: DataHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 600000
      # 最大连接数
      maximum-pool-size: 60
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间
      max-lifetime: 1800000
      # 连接超时时间
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  # redis
  redis:
    host: 192.168.3.73
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 20
        min-idle: 5
# mybatis-plus配置
mybatis-plus:
  # 配置mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: fun.mizhuo.seckill.pojo

# Mybatis SQL打印(方法所在包，不上mapper.xml所在)
logging:
  level:
    fun.mizhuo.seckill.mapper: debug

