server:
  port: 2000
spring:
  application:
    name: spike-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
          - classPath:/shared
      profile: dev
eureka:
  instance:
    hostname: localhost
    port: 8001
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
      fetch-registry: true