/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_example_demo_NativeTest */

#ifndef _Included_com_example_demo_NativeTest
#define _Included_com_example_demo_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_NativeTest
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_demo_NativeTest_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     com_example_demo_NativeTest
 * Method:    callBack
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_demo_NativeTest_callBack
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
