server:
  port: 8929
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
      routes: #配置路由路径
        - id: marry-auth
          uri: lb://marry-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: marry-portal
          uri: lb://marry-portal
          predicates:
            - Path=/portal/**
          filters:
            - StripPrefix=1
        - id: marry-friends
          uri: lb://marry-friends
          predicates:
            - Path=/friends/**
          filters:
            - StripPrefix=1
        - id: marry-goods
          uri: lb://marry-goods
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8029/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/favicon.ico"
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/auth/rsa/publicKey"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logstash:
  host: localhost
logging:
  level:
    site:
      mizhuo:
        marry:
          mapper: DEBUG