server:
  port: 8888
spring:
  application: transaction
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mizhuo123
    url: jdbc:mysql://192.168.3.73:3306/demo
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logstash:
  host: 192.168.204.128
logging:
  level:
    com:
      baomidou:
        mybatisplus: DEBUG
    site:
      mizhuo:
        springtransaction:
          mapper: DEBUG