server:
  port: 8001
eureka:
  instance:
    hostname: localhost
    port: 8001
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/